### ISSUE TITLE
Unpack error

### ISSUE THREAD

**Issue by Stanzilla** [jslicense/spdx-expression-parse.js#1]
npm ERR! tar.unpack untar error /home/vagrant/.npm/spdx-expression-parse/1.0.0/package.tgz

**Comment by kemitchell** [comment]
Interrupted install maybe? Can you reproduce with a clean cache?

**Comment by Stanzilla** [comment]
Yeah, sadly I can.

```
vagrant@homestead:/home/sites/weakauras$ sudo npm cache clean -f
npm WARN using --force I sure hope you know what you are doing.
vagrant@homestead:/home/sites/weakauras$ sudo npm install --no-bin-links
npm ERR! tar.unpack untar error /home/vagrant/.npm/spdx-expression-parse/1.0.0/package.tgz
```

**Comment by kemitchell** [comment]
Thanks for verifying. Really appreciate it.

I will have a look. Would a semver-patch release do it for you?

**Comment by Stanzilla** [comment]
Yeah I think that would be fine, thanks :)

**Comment by kemitchell** [comment]
Hmm. The tarball in public registry seems fine:

``` shellsession
$ wget $(npm info spdx-expression-parse dist.tarball)
...
$ file spdx-expression-parse-1.0.0.tgz
spdx-expression-parse-1.0.0.tgz: gzip compressed data, from Unix
$ tar tvf spdx-expression-parse-1.0.0.tgz
-rw-r--r-- 1000/1000       801 2015-08-01 20:21 package/package.json
-rw-r--r-- 1000/1000      1019 2015-08-01 20:19 package/README.md
-rw-r--r-- 1000/1000      1096 2015-08-01 20:19 package/LICENSE
-rw-r--r-- 1000/1000       126 2015-08-01 20:19 package/index.js
-rw-r--r-- 1000/1000     36971 2015-08-01 20:24 package/parser.generated.js
$ tar zxvf spdx-expression-parse-1.0.0.tgz
package/package.json
package/README.md
package/LICENSE
package/index.js
package/parser.generated.js
```

I was also able to install from registry using Node v4.2.1 and npm v 3.3.6. Might you try installing on a different machine?

``` shellsession
~ % cd $(mktemp -d)
/tmp/tmp.yTuOxzrJ00 % npm i --save
/tmp/tmp.yTuOxzrJ00 % npm i spdx-expression-parse
/tmp/tmp.yTuOxzrJ00
└─┬ spdx-expression-parse@1.0.0
  ├── spdx-exceptions@1.0.3
  └── spdx-license-ids@1.0.2

/tmp/tmp.yTuOxzrJ00 % node
> require('spdx-expression-parse')('MIT')
{ license: 'MIT' }
>
```

I noticed you are in Germany. Thank you for accommodating me in English!

**Comment by Stanzilla** [comment]
Hrm, I think I figured it out. I run vagrant/homestead on a Windows machine, so it runs into ye olde too long file paths problem. That's probably because it errors when unpacking because the file paths would just be too long for it to handle. Certainly one of the most stupid Windows limitations but I heard npm@3 does a flatter structure by default and lo and behold, using npm@3 it installs just fine. Sorry for wasting your time :(

**Comment by kemitchell** [comment]
You didn't waste my time. Thanks for taking time to describe how you resolved the issue.

**Comment by kemitchell** [comment]
Also: You create an issue/bug report at npm/npm, if there isn't one already.
