### ISSUE TITLE
Move to jslicense org

### ISSUE THREAD

**Issue by kemitchell** [jslicense/spdx-expression-parse.js#12]
@shinnn, @cscott, unless you've any objections, I will move this repository to the `jslicense` org and add you both as collaborators: https://github.com/jslicense

First, it's nice to organize things a bit, especially when you have way too many repos.

Second, all the SPDX packages I started have been team efforts. I think the org might help recognize and present that better.

**Comment by shinnn** [comment]
👍 I have no objection to that.

**Comment by kemitchell** [comment]
Done.
