### ISSUE TITLE
`spdx-license-ids` is out of date

### ISSUE THREAD

**Issue by 12joan** [jslicense/spdx-expression-parse.js#30]
The dependency `spdx-license-ids` is out of date.

Current version: 3.0.0
Latest version: 3.0.13

Assuming I'm following the chain of dependencies correctly, this is causing NPM to reject newer licenses like `MIT-0`.
```
warning package.json: License should be a valid SPDX license expression
```

**Comment by ljharb** [comment]
It’s using a range, with ^, so that includes every v3 version. Nothing needs to be done here; just update your lockfile.
