### ISSUE TITLE
Replace the spdx-license-ids and spdx-exceptions packages with upstream data

### ISSUE THREAD

**Issue by sschuberth** [jslicense/spdx-expression-parse.js#33]
The [spdx-license-ids](https://www.npmjs.com/package/spdx-license-ids) and [spdx-exceptions](https://www.npmjs.com/package/spdx-exceptions) packages just contain a single JSON file each. To reduce maintenance effort, I believe it would make sense to replace these with directly using the data from https://github.com/spdx/license-list-data/tree/main/json in this project.

**Comment by kemitchell** [comment]
I maintain all the relevant packages and prefer to track them separately.

**Comment by ljharb** [comment]
I agree; consolidation increases maintenance effort, it doesn’t decrease it.

**Comment by sschuberth** [comment]
To clarify, the background of my request was that upstream updates seem to go unnoticed... https://github.com/jslicense/spdx-exceptions.json hasn't been updated in 4 years (despite [a PR being ready to merge](https://github.com/jslicense/spdx-exceptions.json/pull/11)), missing exceptions like [Autoconf-exception-generic](https://spdx.org/licenses/Autoconf-exception-generic.html).
