### ISSUE TITLE
Autoconf-exception-generic missing from exceptions

### ISSUE THREAD

**Issue by Etsija** [jslicense/spdx-expression-parse.js#34]
Is there a reason why Autoconf-exception-generic is missing from [spdx-exceptions](https://github.com/jslicense/spdx-exceptions.json/blob/master/index.json)? It seems to be a valid exception, according to the [SPDX definition](https://spdx.org/licenses/exceptions-index.html).

**Comment by sschuberth** [comment]
Also see https://github.com/jslicense/spdx-exceptions.json/pull/11, which for whatever reason was not merged.

**Comment by sschuberth** [comment]
@Etsija it's [there](https://github.com/jslicense/spdx-exceptions.json/blob/be44e6208e69b2a604deabae66a42f50dc77390d/index.json#L6) now, so this can be closed.
